// assets/react/controllers/ChoiceType.jsx
import React, { useState, useEffect }  from 'react';
import {toString, getList} from '../../js/utils'

export default function ChoiceType({id, name, className, value, label}) {
    const [list, setList] = useState([]);
    const [selectedValue, setSelectedValue] = useState(value);

    useEffect(() => {
        const list = getList(`api_${className}_list`)
            .then((list) => setList(list))
    }, [])

    return (
        <div className='form-group'>
            <label htmlFor={id}>{label }</label>
            <select value={selectedValue} onChange={(event) => setSelectedValue(event.target.value)} className="form-control form-control-sm" name={name} id={id}>
                {list.map((entity) => 
                    <option key={entity.id} value={entity.id} >{toString(entity)}</option>
                )}
            </select>
        </div>
    )
}

// assets/vue/controllers2/ChoiceType.vue
<template>
    <label for="id">{{ label }}</label>
    <select v-model="selected" class="form-control form-control-sm" :name="name" :id="id">
        <option v-for="entity in store.list[this.className]" :key="entity.id" :value="entity.id">{{ store.toSring(entity) }}</option>
    </select>
</template>

<script>

import { store } from './store.js'

export default {
    props: {
        id: String,
        name: String,
        className: String,
        exclude: String,
        value: String,
        label: String,
    },
    data() {
        return {
            store,
        }
    },
    created() {
        this.store.getList(this.className);
        this.selected = this.value;
    },
}
</script>
