// assets/vue/controllers/Edit.vue
<template>
    <div class="modal" :class="{'fade': edit}" tabindex="-1" role="dialog">           
        <div class="modal-dialog" :class="{ 'modal-open': edit, size: size }" role="document">
            <div v-if="loaded" class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" @click="hide" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">{{ title }}</h4>
                </div>
                <form :action="form.action" @submit.prevent="onSubmit">
                    <div v-html="form.elements" class="modal-body"></div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" @click="hide">Annuler</button>
                        <button type="submit" class="btn" :class="theme">{{ form.submit }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</template>

<script>

import { store } from './store.js'
import { checkStatus, isJsonResponse } from './../../js/fetch.js'

export default {
    props: {
        edit: Boolean,
        size: String,
        route: String,
    },
    emits: [
        'update:edit'
    ],
    data() {
        return {
            title: null,
            content: null,
            theme: null,
            form: {},
            loaded: false,
            store,
        }
    },

    methods: {
        async onLoad() {           
            await fetch(this.route)
            .then(checkStatus)
            // .then(isJsonResponse)
            .then((response) => response.json())
            .then((json)=> {
                this.form = json.form;
                this.title = json.title;
                this.theme = json.theme;
                this.loaded = true;
                console.log('children', this.form.children)
            });
        },
        async onSubmit(event) {
            const form = event.target;
            Array.from(form.elements).forEach((element) => {
                if ('-1' === element.value) {
                    element.value = null;
                }
            })
            await fetch(form.action, {
                method: 'POST',
                body : new FormData(form),
            })
            .then(checkStatus)
            // .then(isJsonResponse)
            .then((response) => {
                console.log('response', response); return response.json()})
            .then((json)=> {
                console.log('response', json)
                if (json.success) {
                    store.update(json.data);
                    this.hide(); 
                }
                if (json.form) {
                    this.form = json.form;
                }
            });
        },
        hide() {
            this.$emit('update:edit', false);
            setTimeout(() => {
                this.loaded = false;
                this.form = {};
            }, 500);
        }
    },
    updated() {
        if (this.edit && this.route && !this.loaded) {
            this.onLoad();
        }
    },
    created() {
        console.log('Edit.vue')
        
    },
}
</script>

// assets/react/components/Edit.jsx
import React, { useState, useEffect } from 'react';
import { checkStatus, isJsonResponse } from './../../js/fetch.js'

export default function Edit({edit, size, route, handleEditChange, update}) {

    const [title, setTitle] = useState('');
    const [theme, setTheme] = useState(null);
    const [form, setForm] = useState({});
    const [loaded, setLoaded] = useState(false);
    
    useEffect(() => {
        
        
    }, [])

    const load = () => {
        console.log('useEffect', edit, route, loaded)
        if (edit && route && !loaded) {
            fetch(route)
                .then(checkStatus)
                .then(isJsonResponse)
                .then((response) => response.json())
                .then((json)=> {
                    console.log('fetch edit', json)
                    setForm(json.form);
                    setTitle(json.title);
                    setTheme(json.theme);
                    setLoaded(true);
                });
        }
    }

    const onSubmit = (event) => {
        event.preventDefault();
        const form = event.target;
        console.log('submit', form)
        Array.from(form.elements).forEach((element) => {
            if ('-1' === element.value) {
                element.value = null;
            }
        })
        fetch(form.action, {
            method: 'POST',
            body : new FormData(form),
        })
        .then(checkStatus)
        .then(isJsonResponse)
        .then((response) => response.json())
        .then((json)=> {
            console.log('response', json)
            if (json.success) {
                update(json.data)
                hide(); 
            }
            if (json.form) {
                setForm(json.form);
            }
        });
    }
    const hide = () => {
        handleEditChange(false);
        setTimeout(() => {
            setLoaded(false);
            setForm({});
        }, 500);
    }
    const createMarkup = () => {
        console.log('form.element', form.elements)
        return {__html: form.elements};
    }

    const ModalContent = () => {
        console.log('loaded', loaded)
        load();
        if (loaded) {
            return (
                <div className="modal-content">
                    <div className="modal-header">
                        <button type="button" className="close" onClick={hide} aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 className="modal-title">{ title }</h4>
                    </div>
                    <form action={form.action} onSubmit={(event) => onSubmit(event)}>
                        <div dangerouslySetInnerHTML={createMarkup(form.elements)} className="modal-body"></div>
                        <div className="modal-footer">
                            <button type="button" className="btn btn-default" onClick={hide}>Annuler</button>
                            <button type="submit" className={'btn ' + theme}>{ form.submit }</button>
                        </div>
                    </form>
                </div>
            )
        }
    }

    return (<div className={(edit) ? 'modal fade' : 'modal'} tabIndex="-1" role="dialog">           
        <div className={(edit) ? 'modal-dialog modal-open ' + size : 'modal-dialog '+ size } role="document">
            <ModalContent />
        </div>
    </div>)
}
