// assets/vue/controllers/RadioType.vue
<template>
    <div className="radio-group-vue" v-for="choice in choices" :key="choice.value">
        <input type="radio" :name="name" :id="choice.id" :value="choice.value" v-model="picked">
        <label className="label" :for="choice.id" :style="{'background-color': getBackground(choice)}">{{ choice.label }}</label>
    </div>
</template>


<script>

export default {
    props: {
        name: String,
        value: String,
        choices: Array,
    },
    data() {
        return {
            picked: null,
        }
    },
    methods: {
        getBackground(choice) {
            if (this.picked === choice.value) {
                return  choice.color;
            }
            return 'unset';
        }
    },
    created() {
        console.log('choices', this)
        this.picked = this.value;
    },
}
</script>

// assets/react/components/RadioType.jsx
import React, { useState }  from 'react';

export default function RadioType({id, name, label, choices, value, className}) {
    const [picked, setPicked] = useState(value);

    const getBackground = (choice) => {
        if (picked === choice.value) {
            return  choice.color;
        }
        return 'unset';
    }

    return (
        <div className={className}>
            <label htmlFor={id}>{label }</label>
            {choices.map((choice) => 
                <div className="radio-group-vue" key={choice.value}>
                    <input type="radio" name={name} id={choice.id} value={choice.value} onClick={(event) => setPicked(event.target.value)} checked={picked === choice.value}/>
                    <label className="label" htmlFor={choice.id} style={{'backgroundColor': getBackground(choice)}}>{ choice.label }</label>
                </div>
            )}
        </div>
    )
}
