// assets/react/components/ChoiceFilteredType.jsx
import React, { useState, useEffect }  from 'react';
import {toString, getList, getListFiltered} from '../utils'

export default function ChoiceFilteredType({id, name, entityName, label, filters, mainList, className}) {
    const [list, setList] = useState([]);
    const [selectedValue, setSelectedValue] = useState('');

    useEffect(() => {
        const list = getData(`api_${entityName}_list`)
            .then((data) => setList(data.list))
    }, [])

    const listFiltered = () => {
        return getListFiltered(list, filters, mainList);
    }

    return (
        <div className={className}>
            <label htmlFor={id}>{label }</label>
            <select value={selectedValue} onChange={(event) => setSelectedValue(event.target.value)} className="form-control form-control-sm" name={name} id={id}>
                {listFiltered().map((entity) => 
                    <option key={entity.id} value={entity.id} disabled={entity.disabled} >{toString(entity)}</option>
                )}
            </select>
        </div>
    )
}

// assets/vue/controllers/ChoiceFilteredType.vue
<template>
    <select v-model="selected" class="form-control form-control-sm">
        <option v-for="entity in store.listFiltered(className, exclude)" :key="entity.id" :value="entity.id" :disabled="entity.disabled">{{ store.toSring(entity) }}</option>
    </select>
</template>

<script>

import { store } from './store.js'

export default {
    props: {
        className: String,
        exclude: String,
        
    },
    data() {
        return {
            store,
            select: undefined,
        }
    },
    created() {
        this.store.getList(this.className);

    },
}
</script>
